const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");

module.exports.config = {
  name: "imagine",
  version: "4.5.0",
  credits: "SARDAR RDX",
  description: "Advanced Text-to-Image using Gemini NanoBanana Engine",
  commandCategory: "AI-Graphics",
  usages: "[any prompt]",
  cooldowns: 15
};

module.exports.run = async ({ api, event, args }) => {
  const { threadID, messageID } = event;
  const prompt = args.join(" ");

  if (!prompt) {
    return api.sendMessage("⚠️ Ustad ji, kuch toh imagine karwayein!\n\nExample: #imagine a samurai cat in cyberpunk city", threadID, messageID);
  }

  // 🎨 Professional Waiting Message
  const waitMsg = await api.sendMessage(`🌌 **𝐀𝐇𝐌𝐀𝐃 𝐑𝐃𝐗 𝐈𝐌𝐀𝐆𝐈𝐍𝐀𝐓𝐈𝐎𝐍**\n━━━━━━━━━━━━━━━\n🧠 **AI Engine:** Gemini NanoBanana\n🔮 **Prompt:** ${prompt}\n⌛ Visualizing your thoughts...\n━━━━━━━━━━━━━━━`, threadID);

  try {
    const cachePath = path.join(__dirname, "cache", `imagine_${Date.now()}.png`);
    fs.ensureDirSync(path.join(__dirname, "cache"));

    // 🔗 Aapka Render API Link (Fixed Endpoint)
    // Style 'none' rakha hai taake general image bane
    const apiUrl = `https://imagine-nsac.onrender.com/api/generate?prompt=${encodeURIComponent(prompt)}&style=none`;

    const response = await axios.get(apiUrl, { responseType: 'arraybuffer', timeout: 80000 });
    
    // Check if response is actually an image
    if (response.headers['content-type'].includes('application/json')) {
        throw new Error("API returned JSON instead of Image");
    }

    fs.writeFileSync(cachePath, Buffer.from(response.data));

    // Wait message ko delete karna
    api.unsendMessage(waitMsg.messageID);

    return api.sendMessage({
      body: `🦅 **𝐈𝐌𝐀𝐆𝐈𝐍𝐀𝐓𝐈𝐎𝐍 𝐂𝐎𝐌𝐏𝐋𝐄𝐓𝐄**\n━━━━━━━━━━━━━━━\n🎨 **Prompt:** ${prompt}\n✨ Generated by Ahmad RDX AI\n━━━━━━━━━━━━━━━`,
      attachment: fs.createReadStream(cachePath)
    }, threadID, () => {
        if (fs.existsSync(cachePath)) fs.unlinkSync(cachePath);
    }, messageID);

  } catch (e) {
    api.unsendMessage(waitMsg.messageID);
    console.error(e);
    
    let errorMsg = "❌ AI is dreaming too hard! (Server Timeout).";
    if (e.response && e.response.status === 500) {
        errorMsg = "❌ Backend Error: Cookie expire ho gayi ya API limit reach ho gayi.";
    }
    
    return api.sendMessage(errorMsg, threadID, messageID);
  }
};
